language: objective-c
before_install: 
 - ./build-libssl.sh verbose
 - xcrun -sdk iphoneos lipo -info ./lib/*.a
script: 
 - xctool -project OpenSSL-for-iOS.xcodeproj -scheme OpenSSL-for-iOS -sdk iphonesimulator clean build