osx_image: xcode13.4
language: objective-c
before_install:
 - ./travis-build.sh

script:
  - xcodebuild -project OpenSSL-for-iOS.xcodeproj -scheme OpenSSL-for-iOS -sdk iphonesimulator clean build ARCHS="x86_64"
